---
# Crash Course Python for Data Science - Intro to Python  
---
# 06 - Numpy
---



## STOP! BEFORE GOING ANY FURTHER...  

Remember, this exercises are open book, open neighbour, open everything! Try to do them on your own before looking at the solution samples.



### Import Numpy as Np

In [1]:
# Make sure you run this cell first
import numpy as np
print('NumPy imported!')

NumPy imported!


### Generate random numbers
Create a (5,3) Numpy array of random integer values between 0 and 100.

In [2]:
array = np.random.randint(0, 101, size=(5, 3))
print(array)

[[38 43 76]
 [77 70 18]
 [39 17 81]
 [46 90  6]
 [79 82 35]]


In [3]:
#@title Double click here for a sample solution

x = np.random.randint(0,100, (5,3))
x

array([[11, 42, 43],
       [49, 26, 54],
       [39, 62, 85],
       [97, 20,  3],
       [26,  0, 97]])

### Array practice

In [5]:
first_row = array[0]
print("1：", first_row)

1： [38 43 76]


In [6]:
#@title Double click here for a sample solution

# Return the first row:
x[0,]

array([11, 42, 43])

In [9]:
last_column = array[:, -1]
print( last_column)

[76 18 81  6 35]


In [0]:
#@title Double click here for a sample solution

# Return last column
x[:, -1]

In [0]:
# Return the third column values from the 4th and 5th rows

### YOUR CODE GOES HERE ###

In [10]:
#@title Double click here for a sample solution

# Return the third column values from the 4th and 5th rows
x[3:5,2]

array([ 3, 97])

In [0]:
# Multiply every value in the array by 2

### YOUR CODE GOES HERE ###

In [11]:
#@title Double click here for a sample solution

# Multiply every value in the array by 2
x*2

array([[ 22,  84,  86],
       [ 98,  52, 108],
       [ 78, 124, 170],
       [194,  40,   6],
       [ 52,   0, 194]])

In [0]:
# Divide every value by 3

### YOUR CODE GOES HERE ###

In [12]:
#@title Double click here for a sample solution

# Divide every value by 3
x/3

array([[ 3.66666667, 14.        , 14.33333333],
       [16.33333333,  8.66666667, 18.        ],
       [13.        , 20.66666667, 28.33333333],
       [32.33333333,  6.66666667,  1.        ],
       [ 8.66666667,  0.        , 32.33333333]])

In [0]:
# Increase the values in the first row by 12

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Increase the values in the first row by 12
x[0,] = x[0,] + 12
x

In [0]:
# Calculate the mean of the first column

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Calculate the mean of the first column
x[:,0].mean()

In [0]:
# Calculate the median of the array after removing the 2 smallest values in the array

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Calculate the median of the array after removing the 2 smallest values in the array
x1 = np.delete(x, x.argmin())
x1 = np.delete(x1, x1.argmin())
np.median(x1)


In [0]:
# Calculate the standard deviation of the first 3 rows

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Calculate the standard deviation of the first 3 rows
np.std(x[:3],)

In [0]:
# Return values in the second column greater than 25

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Return values in the second column greater than 25
print("Values bigger than 25 on the second column =", x[:,1][x[:,1]>25])

In [0]:
# Return values in the array under 40

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Return values in the array under 40
print("Values under 40 in array =", x[x<40])